# Generated by Django 2.0.9 on 2018-12-30 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascota', '0006_mascota_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('historias', models.TextField()),
                ('fecha', models.DateField()),
                ('like', models.IntegerField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('titulo', models.CharField(max_length=250)),
                ('id_adoptivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota')),
            ],
        ),
    ]
