# Generated by Django 2.0.9 on 2018-12-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptivo',
            fields=[
                ('id_adoptivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('ci_adop', models.CharField(max_length=11)),
                ('direccion', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
