# Generated by Django 2.0.9 on 2018-12-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('ci_pro', models.CharField(max_length=250)),
                ('raza', models.CharField(blank=True, max_length=250)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('pelo', models.CharField(max_length=250)),
                ('tamanio', models.CharField(max_length=250)),
                ('sexo', models.CharField(max_length=50)),
                ('alergia', models.CharField(blank=True, max_length=10)),
                ('tratamiento', models.CharField(blank=True, max_length=10)),
                ('enfermeda', models.CharField(blank=True, max_length=10)),
                ('adultos', models.CharField(blank=True, max_length=10)),
                ('niños', models.CharField(blank=True, max_length=10)),
                ('perros', models.CharField(blank=True, max_length=10)),
                ('otros', models.CharField(blank=True, max_length=10)),
                ('jugueton', models.IntegerField()),
                ('curioso', models.IntegerField()),
                ('tranquilo', models.IntegerField()),
                ('educado', models.IntegerField()),
                ('deportista', models.IntegerField()),
                ('carinioso', models.IntegerField()),
                ('mihistoria', models.TextField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
