# Generated by Django 2.0.9 on 2018-12-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
