# Generated by Django 2.0.9 on 2018-12-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_mascota_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='niños',
            new_name='ninios',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='curioso',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='pelo',
        ),
    ]
