# Generated by Django 2.0.9 on 2018-12-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20181226_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='deportista',
        ),
    ]
